AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EcommerceDigitalPrintsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ecommerce.digital-prints
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        # - AttributeName: orderStatus
        #   AttributeType: S
        - AttributeName: requestId
          AttributeType: S
      KeySchema:
        - AttributeName: requestId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
