# Tile Engine Status Code List
ENGINE_SUCCESS = 0

# Engine error not caught
ENGINE_FAILURE_CRITICAL = 1

# Engine step failures
DOWNLOADER_FAILURE = 2
ASSEMBLER_FAILURE = 3
TEXT_FAILURE = 4
BORDER_FAILURE = 5
DYNAMO_DB_FAILURE = 6
S3_POST_FAILURE = 7
