# Tile Engine Status Code List
ENGINE_SUCCESS = 0

# Engine error not caught
ENGINE_FAILURE_CRITICAL = 1

# Engine step failures
DOWNLOADER_FAILURE = 2
# ASSEMBLER_FAILURE = 3
ASSEMBLER_TILES_FAILURE = 4
ASSEMBLER_CROP_BBOX_FAILURE = 5
ASSEMBLER_ADD_PIN_FAILURE = 6
MAIN_RESIZE_FAILURE = 7
ASSEMBLER_ADD_STYLE_FAILURE = 8
ASSEMBLER_ADD_TEXT_FAILURE = 9
ASSEMBLER_ADD_BORDER_FAILURE = 10
TRANSPARENCY_TRANSFORMER_FAILURE = 11

PAYLOAD_VALIDATION_FAILURE = 12
# DYNAMO_DB_FAILURE = 6
# S3_POST_FAILURE = 7
